/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rnimour.messaging.kafka

import org.springframework.boot.test.context.SpringBootTest
import kotlin.test.Test


@SpringBootTest
class AppTest {

    @Test
    fun contextLoads() {
    }
}
