/*
 * This source file was generated by the Gradle 'init' task
 */
package com.rnimour.messaging.kafka

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
open class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
    runApplication<App>(*args)
}
